name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - eli5
  - matplotlib
  - numpy
  - scipy
  - pandas
  - geopandas
  - scikit-learn
  - scikit-plot
  - jupyter
  - shapely
  - hvplot
  - geoviews
  - jupyterlab<3
