#!/bin/bash

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json

# Add jupyterlab extenstions
jupyter labextension install @jupyterlab/toc
jupyter labextension install @pyviz/jupyterlab_pyviz
