#!/bin/bash

# Running notebooks with interactive plots in a trusted state so they appear when the file opens
jupyter trust geospatial/geospatial-basics.ipynb
jupyter trust visualisation/sankey-diagram.ipynb

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json

# Add jupyterlab extensions
jupyter labextension install @jupyterlab/toc
