name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Setup conda environment and Build Slides
      uses: s-weigand/setup-conda@v1.0.1
      with:
        args: | 
          conda env create -n python_workshops -f ../requirements.yml
          conda activate python_workshops
          jupyter nbconvert Decorators_Dataclass_IDE.ipynb --to slides --SlidesExporter.reveal_scroll=True 
    - name: Commit and push files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
        git push origin master
