name: Build Slides

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        environment-file: environment.yml
        activate-environment: notebook
        auto-activate-base: false
    - shell: bash
      run: |
        source usr/share/miniconda3/bin/activate
        cd Decorators_Dataclasses_IDEs/
        jupyter nbconvert Decorators_Dataclasses_IDEs.ipynb --to slides --SlidesExporter.reveal_scroll=True
        mv Decorators_Dataclasses_IDEs.slides.html index.html -f
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "Add changes" -a || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
