name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup-conda
    - uses: s-weigand/setup-conda@v1.0.1
    - name: Make conda environment
    - run: conda create env -f /requirements.yml
    - name: Make slides
      run: jupyter nbconvert Decorators_Dataclass_IDE.ipynb --to slides --SlidesExporter.reveal_scroll=True

