name: Build Slides

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Setup conda environment and Build Slides
      uses: s-weigand/setup-conda@v1.0.1
      with:
        activate-conda: false
        args: | 
          conda env create -n python_workshops -f ../requirements.yml
          conda activate python_workshops
          jupyter nbconvert ../Decorators_Dataclasses_IDE.ipynb --to slides --SlidesExporter.reveal_scroll=True
          echo ls
          cd ..
          echo ls
          cd ..
          echo ls
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
