name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.1
      with:
        args: conda env create -f ../requirements.yml | jupyter nbconvert Decorators_Dataclass_IDE.ipynb --to slides --SlidesExporter.reveal_scroll=True
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
