name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.1
      with:
        args: conda env create -f ../requirements.yml | jupyter nbconvert Decorators_Dataclass_IDE.ipynb --to slides --SlidesExporter.reveal_scroll=True
